# Java Gradle CircleCI 2.0 configuration file
#
# Check https://circleci.com/docs/2.0/language-java/ for more details
#
version: 2
jobs:
  build:
    working_directory: ~/MobileAppAutomationTest
    docker:
        - image: circleci/android:api-28-alpha
    environment:
        GRADLE_OPTS: -Xmx4g -Dorg.gradle.daemon=false
        JVM_OPTS: -Xmx4g
    steps:
      - checkout
      - restore_cache:
          key: gradle-{{ checksum "AndroidDemo/build.gradle" }}-{{ checksum  "AndroidDemo/app/build.gradle" }}-{{ checksum  "AndroidDemo/gradle/wrapper/gradle-wrapper.properties" }}
      - run:
          name: Download Dependencies
          command: ./gradlew androidDependencies
      - save_cache:
          paths:
          - ~/.gradle
          key: gradle-{{ checksum "AndroidDemo/build.gradle" }}-{{ checksum  "AndroidDemo/app/build.gradle" }}-{{ checksum  "AndroidDemo/gradle/wrapper/gradle-wrapper.properties" }}
      - run:
          name: Uninstall crcmod
          command: echo "y" | sudo pip uninstall crcmod
      - run:
          name: Install crcmod
          command: sudo pip install -U crcmod
      - run:
          name: Run instrumentation tests in Firebase Test Lab
          command: bundle exec fastlane instrumentation_tests_testlab
      - store_artifacts:
          path: firebase/
          destination: /firebase/
